name: worktide-portal
type: php
docroot: ""
webserver_type: nginx-fpm
disable_settings_management: true
omit_containers: [db]
corepack_enable: true
nodejs_version: "22"

web_extra_exposed_ports:
  - name: vite
    container_port: 5174
    http_port: 5172
    https_port: 5174

web_extra_daemons:
  - name: "vite"
    command: bash -c 'corepack use pnpm@latest 2>/dev/null; pnpm install --frozen-lockfile --silent 2>/dev/null; pnpm dev'
    directory: /var/www/html
